# Generated by Django 5.0.1 on 2025-02-04 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='rest_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_places.restplace'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='rest_places',
            field=models.ManyToManyField(related_name='amenities', to='rest_places.restplace'),
        ),
    ]
