# Generated by Django 5.0.1 on 2025-02-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_places', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restplace',
            name='city',
            field=models.CharField(default='Bangalore', max_length=100),
        ),
        migrations.AddField(
            model_name='restplace',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='restplace',
            name='state',
            field=models.CharField(default='Karnataka', max_length=100),
        ),
    ]
